# Generated by Django 5.1.1 on 2024-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('illness', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('patient_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(default='Admitted', max_length=10)),
                ('date_admitted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
